project:
  type: website
  output-dir: docs

website:
  title: "Lisa May Ceramics"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - href: contact.qmd
        text: Contact
      - href: about.qmd
        text: About
  page-footer:
    left: "Â© 2024 Lisa May Ceramics"
    right: "All rights reserved. Images may not be used without permission."
      

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true


