project:
  type: website
  output-dir: docs

website:
  title: "Lisa May Ceramics"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - href: contact.qmd
        text: Contact
      - href: about.qmd
        text: About
      

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true


