project:
  type: website
  output-dir: docs

website:
  title: "Lisa May Ceramics"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - href: mugs.qmd
        text: Mugs
      - href: contact.qmd
        text: Contact
      - href: about.qmd
        text: About
  page-footer:
    left: "Â© 2025 Lisa May Ceramics. All rights reserved. Images may not be used without permission."
      

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true


